Update msbuild.yml

diff --git a/.github/workflows/msbuild.yml b/.github/workflows/msbuild.yml
--- a/.github/workflows/msbuild.yml
+++ b/.github/workflows/msbuild.yml
@@ -32,8 +32,14 @@ jobs:
 
     - name: Install Qt VS add-in
       run: |
-        "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vsixinstaller.exe" /q qt-vsaddin-msvc2022-3.0.2.vsix
-      shell: cmd
+        $vsixInstallerPath = (Get-ChildItem -Recurse -Filter vsixinstaller.exe -ErrorAction SilentlyContinue | Where-Object { $_.FullName -match "Microsoft Visual Studio" }).FullName
+        if ($vsixInstallerPath) {
+          & $vsixInstallerPath /quiet qt-vsaddin-msvc2022-3.0.2.vsix
+        } else {
+          Write-Error "vsixinstaller.exe not found."
+          exit 1
+        }
+      shell: pwsh
 
     - name: Set Qt version in Visual Studio
       run: |
