Update msbuild.yml

diff --git a/.github/workflows/msbuild.yml b/.github/workflows/msbuild.yml
--- a/.github/workflows/msbuild.yml
+++ b/.github/workflows/msbuild.yml
@@ -16,6 +16,15 @@ jobs:
     - name: Checkout repository
       uses: actions/checkout@v2
 
+    - name: Verify Visual Studio 2022 installation
+      run: |
+        $vswherePath = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
+        if (-Not (Test-Path $vswherePath)) {
+          Write-Error "vswhere.exe not found. Visual Studio 2022 might not be installed."
+          exit 1
+        }
+        & $vswherePath -latest -version [17.0,18.0) -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
+
     - name: Download Qt VS Add-in
       run: |
         $url = "https://mirror.netcologne.de/qtproject/development_releases/vsaddin/3.0.2/qt-vsaddin-msvc2022-3.0.2.vsix"
@@ -30,6 +39,19 @@ jobs:
           throw "Hash mismatch: $($fileHash.Hash)"
         }
 
+    - name: Find VSIXInstaller
+      id: find-vsix
+      run: |
+        $vswherePath = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
+        $vsInstallPath = & $vswherePath -latest -version [17.0,18.0) -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
+        $vsixInstallerPath = Join-Path -Path $vsInstallPath -ChildPath "Common7\IDE\VSIXInstaller.exe"
+        if (-Not (Test-Path $vsixInstallerPath)) {
+          Write-Error "VSIXInstaller.exe not found."
+          exit 1
+        }
+        echo "::set-output name=vsixInstallerPath::$vsixInstallerPath"
+
     - name: Install Qt VS Add-in
       run: |
-        Start-Process "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VSIXInstaller.exe" -ArgumentList "/q", "qt-vsaddin-msvc2022-3.0.2.vsix" -Wait
+        $vsixInstallerPath = "${{ steps.find-vsix.outputs.vsixInstallerPath }}"
+        Start-Process $vsixInstallerPath -ArgumentList "/q", "qt-vsaddin-msvc2022-3.0.2.vsix" -Wait
